{{- if and .Values.auth.token (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exalm-agent.fullname" . }}-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "exalm-agent.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  dashboard-token: {{ .Values.auth.token | quote }}
{{- end }}
